### ISSUE TITLE
input of size [0] 

### ISSUE THREAD

**Issue by HilmiK** [yueruchen/Pedestrian-Synthesis-GAN#10]
Hi,

I got the error with my custom dataset which has size of 256x128.

  File "/usr/local/lib/python2.7/dist-packages/torch-0.4.1-py2.7-linux-x86_64.egg/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 3, 4, 4], but got input of size [0] instead.

Thanks in advance.

**Comment by yueruchen** [comment]
Could you please print the size of the input to this layer?

**Comment by HilmiK** [comment]
torch.Size([0]) spp_x is the input to this layer. Full traceback follows such that :

  File "train.py", line 37, in <module>
    model.optimize_parameters(only_d)
  File "/home/hilmi/Desktop/tez/Pedestrian-Synthesis-GAN/models/pix2pix_model.py", line 188, in optimize_parameters
    self.backward_D_person()
  File "/home/hilmi/Desktop/tez/Pedestrian-Synthesis-GAN/models/pix2pix_model.py", line 140, in backward_D_person
    self.person_fake = self.netD_person.forward(self.person_crop_fake)
  File "/home/hilmi/Desktop/tez/Pedestrian-Synthesis-GAN/models/networks.py", line 472, in forward
    x = self.conv1(x)
  File "/usr/local/lib/python3.5/dist-packages/torch-0.4.1-py3.5-linux-x86_64.egg/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch-0.4.1-py3.5-linux-x86_64.egg/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 3, 4, 4], but got input of size [0] instead

**Comment by yueruchen** [comment]
Have you calculated the output of the D_P? Since it accepts the cropped images you should custom the D_P according to the size of cropped images.

**Comment by HilmiK** [comment]
No, I think I did not calculate that. Could you pls tell me which part of the code should I modify ?

**Comment by yueruchen** [comment]
You should take care of it but I think this bug is not caused by that problem.
Seems the there is some problem before the tensor sent to the D_P. It should not cause any problem since we have successfully used it. You'd better check whether you have changed any part.

**Comment by HilmiK** [comment]
I changed my input size 256x128 unlike you did experiments in 512x256. Hence, I modified Unet128, loadSize, fineSize. Can they be problem?

**Comment by yueruchen** [comment]
You should particularly check the json file in the dataset. In our code, "w" and "h" do not represent width and height but the right and bottom coordinate. It's an old bug, you may check this problem.

**Comment by HilmiK** [comment]
Yes, I noticed that and made my annotations according to what you have said. Let me try to find out a solution and post here after I found.

**Comment by sevmardi** [comment]
hi @HilmiK  I know this is off topic, sorry for that. Would you mind sharing you steps on how to pre-process the data? From cityscape for instance, if you happen to use this one.

**Comment by HilmiK** [comment]
Hi @sevmardi , I do not think codes will help you since my annotation format were different from cityscape and I cropped 128x128 patches from image. Are you asking for steps in general ?

**Comment by sevmardi** [comment]
Yeah.. actually formatting is not an issue. Would be great if you could upload it github just to have a look at it general. Sharing the steps would be helpful as well.

**Comment by HilmiK** [comment]
I have  used combine.py in pix2pix tensorflow repo to fuse two images(noisy and normal) as the last step. Other than that, I will upload my part into github tomorrow most probably.

**Comment by sevmardi** [comment]
Will have a look at the mentioned file. Please let me know once uploaded. Thanks!

**Comment by HilmiK** [comment]
I did this after you get y1,y2,x1 and x2:

            sub_img = img[y1:y2,x1:x2]
            sub_img = cv2.cvtColor(sub_img, cv2.COLOR_BGR2GRAY)
            shape = sub_img.shape
            for row in range(shape[0]):
                for col in range(shape[1]):
                    rnd = random.randint(0,1)
                    sub_img[row,col] = rnd*255
            
            img[y1:y2,x1:x2,0]=sub_img
            img[y1:y2,x1:x2,1]=sub_img
            img[y1:y2,x1:x2,2]=sub_img

**Comment by sevmardi** [comment]
But how do you select the pedestrian? 
Were you able to upload your code?

**Comment by HilmiK** [comment]
@sevmardi I am working on cars, not pedestrians and my dataset is different. So, I can not comment on selecting pedestrians. If you can tell me the format of your dataset, maybe an example of annotation, I may help. I think you have a problem with parsing your dataset, am I right ?
