### ISSUE TITLE
Updates generator every step

### ISSUE THREAD

**Issue by OlofHarrysson** [yueruchen/Pedestrian-Synthesis-GAN#12]
Hey, the code looks like this

```
if iter_d <= CRITIC_ITERS-1:
    only_d = False
else:
    only_d = False
```

Is this just a silly bug or are there models where you want to update the generator every time? The cycle-GAN doens't even take the parameter only_d.

**Comment by yueruchen** [comment]
This step is designed to update generator multiple times in each iteration.

**Comment by OlofHarrysson** [comment]
Normally you might want to update the discriminator multiple times each iteration. Don't you think "only_d" stands for "only_discriminator"? And do I really have to point out the obvious here? The code does nothing. The if else statement both put the only_d variable to the same value.

**Comment by yueruchen** [comment]
Yes, as you said, the code does not make any effort here, just forget to delete it.

But it also means that we tried to change the updating times for G or D but do not see difference.

**Comment by OlofHarrysson** [comment]
Okok, thanks for answering. So was the code like this for the results in the paper?

**Comment by yueruchen** [comment]
Yes
