### ISSUE TITLE
Replacing pedestrians in the bounding box

### ISSUE THREAD

**Issue by sevmardi** [yueruchen/Pedestrian-Synthesis-GAN#13]
In the paper you say

> We replace the pedestrians in the bounding boxes with
random noise and train the generator G to synthesize new pedestrians within
that noise region.

How are you selecting the pedestrian in the first place? Are you using object detection to detect the pedestrians on the road (assume cityscape data for now)? And then you apply the noise after getting the y1, y2, x1, x2 ??

Or just manually drawing a bounding-box around a pedestrian and then you apply noise within the box? 
If the latter, what if I would like to pre-process, lets say 10.000 images? 

Please shed some light on this.

**Comment by yifanjiang19** [comment]
Cityscapes dataset provides semantic label for each object. Just choose the maximum and minimum pixel value to get the bounding box information.

**Comment by sevmardi** [comment]
I see. Do you have an example? 
Actually, I don't seem to understand this. Please provide an example. Very short-sighted .

**Comment by sevmardi** [comment]
Hey @yueruchen do you have any examples or references regarding your suggestion?

**Comment by yifanjiang19** [comment]
You need to download the dataset firstly. https://www.cityscapes-dataset.com
It provides sufficient data and label. It is a simple way to convert the pixel label to bounding box. And we will not provide any additional code.
