### ISSUE TITLE
how to prepare dataset

### ISSUE THREAD

**Issue by TJUXJH** [yueruchen/Pedestrian-Synthesis-GAN#15]
hi, I down the gtFine_trainvaltest and gtBbox_cityPersons_trainval from cityscape dataset. however the picture and the label are not like that you show in your dataset. 

Could u please upload the dataset or give me an link to download ? 

What's more, I have no idea how to prepare the data in large quantities？Do u select the picture using machine or by yourself?

Thank for your help in advance

**Comment by TJUXJH** [comment]
Finally, I solve the problem.

**Comment by Arthur-CYS** [comment]
Hello, I encountered the same problem as you, can you ask how you solved it? Thank you!
