### ISSUE TITLE
Why not good performance

### ISSUE THREAD

**Issue by TJUXJH** [yueruchen/Pedestrian-Synthesis-GAN#18]
Hello, Mr Jiang, I need your help again.
Firstly, I make the pedestrian photo like the one you show.
Then I train the model with 280 photos, batchSize=2, and after 1000 epochs, the outputs are like this one:
![output](https://github.com/TJUXJH/pytorch-notebook/blob/images/images/image.png) 
What is the problem and could u please give me some advice to improve the performance?
I hope to get  the performance like the one u show in the paper.
Thank advance!

**Comment by yifanjiang19** [comment]
advices:
1) preparing good training data, especially to avoid overlap between objects.
2) 280 is relatively small, increase training data helps a lot.
3) choose a comparable bounding box size when testing. Eg. If the bounding box size is 170x100 but being changed to 100x50 when testing, the performance will drop a lot.

**Comment by TJUXJH** [comment]
Thanks your advices and your time!
Question about advice 3rd:
oh, actually I never change the bbox size which fit the pedestrian good both in the training and testing.
I downloaded  pedestrian pictures from Cityscape which have different bbox size for each picture, I add noise according to the bbox. 
Do you mean that it's better to chose some pictures which have similar size of bbox for traing and testing?

**Comment by yifanjiang19** [comment]
Yes, actually it is encouraged to avoid bounding box size limitation if you can get enough data.
