### ISSUE TITLE
test error；

### ISSUE THREAD

**Issue by Fyyyyyyyy** [yueruchen/Pedestrian-Synthesis-GAN#2]
Hi,after I run the  "python test.py --dataroot data_path --name model_name --model pix2pix --which_model_netG unet_256 --which_direction BtoA  --dataset_mode aligned --use_spp --no_lsgan --norm batch" .
it turns out "test.py: error: unrecognized arguments: --no_lsgan"
would you please help me with this ?
thanks a lot .

**Comment by yueruchen** [comment]
Thanks,
It is just a mistake, `--no_lsgan` is used on training stage, just delete it when you test the model.

**Comment by Fyyyyyyyy** [comment]
After  ”model [Pix2PixModel] was created”
Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.
And I use Anaconda3 and python3.6 in windows,should I install numpy+mkl version?
thanks a lot

**Comment by Fyyyyyyyy** [comment]
but the pytorch is based on python 3.6,and i don' t know how to change the thread....

**Comment by Fyyyyyyyy** [comment]
Maybe wechat？My id is Alwaysashin，
actually im not so familiar with the code
