### ISSUE TITLE
Data preprocessing code

### ISSUE THREAD

**Issue by azadef** [yueruchen/Pedestrian-Synthesis-GAN#27]
Hello, Thank you for releasing your code. I would like to know if your data preprocessing code for the cityscapes dataset (converting the original dataset to be usable by your code) is available?

**Comment by abinezer** [comment]
@yueruchen hope you could share this code as well...
thanks!

**Comment by yifanjiang19** [comment]
The preprocessing code is too long to be found. Sorry about that. You could build that part follow the guidance in the paper.

**Comment by azadef** [comment]
I have a gist for cityscapes preprocessing: https://gist.github.com/azadef/45733a69ff878766f524cbd9f2a1b13c
