### ISSUE TITLE
How to create a data set

### ISSUE THREAD

**Issue by chl916185** [yueruchen/Pedestrian-Synthesis-GAN#3]
Original Image and Noise Image ，ｈow should the dataset be placed in the datasets?
@yueruchen

**Comment by yueruchen** [comment]
You should create a directory called "images" and another called "bbox". And in each directory there should be two sub-directory called "train" and "test". And then you can place your image data as the demo shows. I put a demo image on "datasets/images/train/", you can follow the rule it makes. And noticed that, you should place the pixel label on the "dataset/bbox/train", the "x, y, w, h" represent "x_left, y_left, x_right, y_right" respectively. "w" and "h" do not means width and height. It's an old unappropriate setting.
