### ISSUE TITLE
thanks for your nice work, but when i have a train with the code, it achieve a mistake, how do i handle it? thanks for your reply.

### ISSUE THREAD

**Issue by feifeiwei** [yueruchen/Pedestrian-Synthesis-GAN#8]
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000229052A80B8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
create web directory ./checkpoints\model_name\web...

**Comment by yueruchen** [comment]
You should first lunch the visdom, run ```python -m visdom.server```
