### ISSUE TITLE
The question about datsets.

### ISSUE THREAD

**Issue by zxt-triumph** [yueruchen/Pedestrian-Synthesis-GAN#9]
When I trained with more than ten pictures, I encountered the following problem：
RuntimeError: Given input size: (512, 5, 3). Calculated output size: (1, 2, 0). Output size is too small.
What should I do？

**Comment by linmelon** [comment]
would you provide the pretrained model

**Comment by zxt-triumph** [comment]
------------ Options -------------
batchSize: 1
beta1: 0.5
checkpoints_dir: ./checkpoints
continue_train: False
dataroot: ./datasets/gun52
dataset_mode: aligned
display_freq: 100
display_id: 1
display_port: 8097
display_single_pane_ncols: 0
display_winsize: 256
fineSize: 256
gpu_ids: [0]
identity: 0.0
input_nc: 3
isTrain: True
lambda_A: 100.0
lambda_B: 10.0
loadSize: 286
lr: 0.0002
max_dataset_size: inf
model: pix2pix
nThreads: 2
n_layers_D: 3
name: gun52_pix2pix
ndf: 64
ngf: 64
niter: 100
niter_decay: 100
no_dropout: False
no_flip: False
no_html: False
no_lsgan: True
norm: batch
output_nc: 3
phase: train
pool_size: 50
print_freq: 100
resize_or_crop: resize_and_crop
save_epoch_freq: 5
save_latest_freq: 5000
serial_batches: False
use_spp: False
which_direction: BtoA
which_epoch: latest
which_model_netD: basic
which_model_netG: unet_256
-------------- End ----------------
CustomDatasetDataLoader
dataset [AlignedDataset] was created
#training images = 52
pix2pix
False
True
---------- Networks initialized -------------
UnetGenerator(
  (model): UnetSkipConnectionBlock(
    (model): Sequential(
      (0): Conv2d (3, 64, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
      (1): UnetSkipConnectionBlock(
        (model): Sequential(
          (0): LeakyReLU(0.2, inplace)
          (1): Conv2d (64, 128, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
          (2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True)
          (3): UnetSkipConnectionBlock(
            (model): Sequential(
              (0): LeakyReLU(0.2, inplace)
              (1): Conv2d (128, 256, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
              (2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True)
              (3): UnetSkipConnectionBlock(
                (model): Sequential(
                  (0): LeakyReLU(0.2, inplace)
                  (1): Conv2d (256, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
                  (2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True)
                  (3): UnetSkipConnectionBlock(
                    (model): Sequential(
                      (0): LeakyReLU(0.2, inplace)
                      (1): Conv2d (512, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
                      (2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True)
                      (3): UnetSkipConnectionBlock(
                        (model): Sequential(
                          (0): LeakyReLU(0.2, inplace)
                          (1): Conv2d (512, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
                          (2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True)
                          (3): UnetSkipConnectionBlock(
                            (model): Sequential(
                              (0): LeakyReLU(0.2, inplace)
                              (1): Conv2d (512, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
                              (2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True)
                              (3): UnetSkipConnectionBlock(
                                (model): Sequential(
                                  (0): LeakyReLU(0.2, inplace)
                                  (1): Conv2d (512, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
                                  (2): ReLU(inplace)
                                  (3): ConvTranspose2d (512, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
                                  (4): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True)
                                )
                              )
                              (4): ReLU(inplace)
                              (5): ConvTranspose2d (1024, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
                              (6): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True)
                              (7): Dropout(p=0.5)
                            )
                          )
                          (4): ReLU(inplace)
                          (5): ConvTranspose2d (1024, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
                          (6): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True)
                          (7): Dropout(p=0.5)
                        )
                      )
                      (4): ReLU(inplace)
                      (5): ConvTranspose2d (1024, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
                      (6): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True)
                      (7): Dropout(p=0.5)
                    )
                  )
                  (4): ReLU(inplace)
                  (5): ConvTranspose2d (1024, 256, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
                  (6): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True)
                )
              )
              (4): ReLU(inplace)
              (5): ConvTranspose2d (512, 128, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
              (6): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True)
            )
          )
          (4): ReLU(inplace)
          (5): ConvTranspose2d (256, 64, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
          (6): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True)
        )
      )
      (2): ReLU(inplace)
      (3): ConvTranspose2d (128, 3, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
      (4): Tanh()
    )
  )
)
Total number of parameters: 54419459
NLayerDiscriminator(
  (model): Sequential(
    (0): Conv2d (6, 64, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
    (1): LeakyReLU(0.2, inplace)
    (2): Conv2d (64, 128, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
    (3): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True)
    (4): LeakyReLU(0.2, inplace)
    (5): Conv2d (128, 256, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1))
    (6): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True)
    (7): LeakyReLU(0.2, inplace)
    (8): Conv2d (256, 512, kernel_size=(4, 4), stride=(1, 1), padding=(1, 1))
    (9): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True)
    (10): LeakyReLU(0.2, inplace)
    (11): Conv2d (512, 1, kernel_size=(4, 4), stride=(1, 1), padding=(1, 1))
    (12): Sigmoid()
  )
)
Total number of parameters: 2769601
PersonDiscriminator(
  (model): Sequential(
    (0): Conv2d (3, 64, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
    (1): LeakyReLU(0.2, inplace)
    (2): Conv2d (64, 128, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
    (3): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True)
    (4): LeakyReLU(0.2, inplace)
    (5): Conv2d (128, 256, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
    (6): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True)
    (7): LeakyReLU(0.2, inplace)
    (8): Conv2d (256, 512, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
    (9): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True)
    (10): LeakyReLU(0.2, inplace)
    (11): Conv2d (512, 1, kernel_size=(4, 4), stride=(1, 1), bias=False)
    (12): Sigmoid()
  )
)
Total number of parameters: 2765568
-----------------------------------------------
model [Pix2PixModel] was created
create web directory ./checkpoints/gun52_pix2pix/web...
Traceback (most recent call last):
  File "train.py", line 37, in <module>
    model.optimize_parameters(only_d)
  File "/home/image/zxt/PS-GAN/models/pix2pix_model.py", line 179, in optimize_parameters
    self.backward_D_person()
  File "/home/image/zxt/PS-GAN/models/pix2pix_model.py", line 131, in backward_D_person
    self.person_fake = self.netD_person.forward(self.person_crop_fake)
  File "/home/image/zxt/PS-GAN/models/networks.py", line 403, in forward
    return nn.parallel.data_parallel(self.model, input, self.gpu_ids)
  File "/home/image/anaconda3/envs/pytorch-0.3/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 110, in data_parallel
    return module(*inputs[0], **module_kwargs[0])
  File "/home/image/anaconda3/envs/pytorch-0.3/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/image/anaconda3/envs/pytorch-0.3/lib/python2.7/site-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/home/image/anaconda3/envs/pytorch-0.3/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/image/anaconda3/envs/pytorch-0.3/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 277, in forward
    self.padding, self.dilation, self.groups)
  File "/home/image/anaconda3/envs/pytorch-0.3/lib/python2.7/site-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: Given input size: (512, 3, 5). Calculated output size: (1, 0, 2). Output size is too small.

**Comment by zxt-triumph** [comment]
The size of input images is 512*256

**Comment by yueruchen** [comment]
@zxt-triumph I don't quite understand the information you provide. Usually pytorch needs the input size to be (B, C, H, W), where B means batch size, C means channel. Here it occurs that the first dimension is 512 which is abnormal.

**Comment by zxt-triumph** [comment]
Thanks for your reply. I have solved the problem.
